# NEMES sandbox (Prompt 9, 19 Eyl 2026).
[Service]
NoNewPrivileges=yes
ProtectSystem=strict
PrivateTmp=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectControlGroups=yes
RestrictSUIDSGID=yes
ReadWritePaths=/home/d3str0y1ng/nemes-testnet/depolama-a /home/d3str0y1ng/.nemes
