[package]
name = "nemes-miner"
version = "0.2.0"
edition = "2021"
description = "NEMES Miner CLI — Full TUI mining (ratatui) + simple log"
publish = false

[[bin]]
name = "nemes-miner"
path = "src/main.rs"

[dependencies]
miner-core = { path = "../miner-core" }
nemes-p2p = { path = "../../nemes-p2p/nemes-p2p" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
reqwest = { workspace = true }
sysinfo = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
indicatif = { workspace = true }
dirs = { workspace = true }
chrono = { workspace = true }
atty = "0.2"
